apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-dz8n
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-dz8n
    app.kubernetes.io/part-of: mc-unsupported-runtime
  name: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-dz8n
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-dz8n
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-dz8n
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-irxn-tenant/mc-unsupported-runtime/devfile-sample-python-basic-rhtap-mc-unsuported-runtime-dz8n@sha256:a8f793432c25181bf4e4d4d3eda74fca049df354905d3eff84f050aa5513d975
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
